USE [master]
GO
ALTER DATABASE [WebSuppliers] SET RECOVERY SIMPLE WITH NO_WAIT
GO
ALTER DATABASE [WebSuppliers] SET RECOVERY SIMPLE --简单模式
GO
USE [WebSuppliers]
GO
DBCC SHRINKFILE (N'WebSuppliers_log' , 11, TRUNCATEONLY) 

USE [master]
GO
ALTER DATABASE [WebSuppliers] SET RECOVERY FULL WITH NO_WAIT
GO
ALTER DATABASE [WebSuppliers] SET RECOVERY FULL --还原为完全模式
GO